"""add source_code to workspaces

Revision ID: d1bbb003f98f
Revises: 3fdd17621eb0
Create Date: 2026-07-22 22:51:35.209291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bbb003f98f'
down_revision = '3fdd17621eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('source_code')

    # ### end Alembic commands ###
